### ISSUE TITLE
Is it possible to include live data in a slide?

### ISSUE THREAD

**Issue by mattlanham** [webslides/WebSlides#136]
Just came across this project and I have been looking for something that will allow me to have many static slides, that information can be added into, but also some dynamic information which is sourced from various data sources.

A quick example to help you understand would be linking into Salesforce API to get a live figure on the number of opportunities that are in the sales pipeline.

Is there a way to have an element on a slide look up a value coming from somewhere else, obviously I'd be able to do the code required to make it integrate, really I'd just want it to make a quick call to service and pull the returned info into a slide? 

If that's not possible now, would creating a plugin for that be theoretically possible for me to do?

**Comment by Antonio-Laguna** [comment]
Hey Matt,

Not sure how are you going to get the data from the Salesforce API. Assuming it's Ajax? You could use the [events](https://github.com/webslides/WebSlides/wiki/Core-API#events-1) to load the data once you enter or you could do a plugin. There's nothing done right now to get live date from anywhere since that'd be too open.

Let me know if you have any other questions!
