### ISSUE TITLE
Navigation doesn't work on tablet devices

### ISSUE THREAD

**Issue by jlantunez** [webslides/WebSlides#79]
This is weird. Tested on iPad (Safari, Chrome, and Firefox). Ryan [uploaded a video](https://twitter.com/OfficialPerEra/status/857230441270697984). We will fix asap!

**Comment by englishextra** [comment]
swipe on android 6.0.1 chrome browser seems to work fine, firfox browser 57.0 slides change in the wrong order - in mystrious ways.

The other importnat thing is why would you use mobile-detector.js
which relies on UA string instead of detecting if touch is available and switch to swipe navigation based on that. It's bad because, say, you cannot debug and test the code on desktop browser with touch events simulation enabled in mobile responsive view - SHFT + CTRL + M in firefox for instance.

So for now I have to disable webslides at all if hasTouch is true or the screen is small so that to reveal all slides and in that case the webslides is useless.

**Comment by Antonio-Laguna** [comment]
Hey @englishextra not sure what the issue is in Firefox, it looks fine to me. What are you experiencing?

We went with the UGLY option because we want to base that on devices, not touch only. Chromebooks, for example, would trigger touch and that wouldn't be intentional.  I was able to debug and test the code on a desktop browser, such as Chrome, as it does change the UA.

Feel free to tinker with the Touch class in your project and adjust it to your needs.

**Comment by englishextra** [comment]
@Antonio-Laguna you pretended not to understand the issue switching the attention to debug issue.
Once again:

> firfox browser 57.0 slides change in the wrong order
that's on android 6 Android 6

**Comment by Antonio-Laguna** [comment]
And you're being pretty rude. I don't have an `android 6 Android 6` so there's no way for me to test that. I answered your concern, not switched attention.

**Comment by englishextra** [comment]
@Antonio-Laguna I'm afraid, you didn't. For now, I just disable the library on touch devices.

**Comment by Antonio-Laguna** [comment]
I did answer, you just didn't like the answer which is another story.

**Comment by englishextra** [comment]
@Antonio-Laguna have a look at this issue here https://github.com/GianlucaGuarini/Tocca.js/issues/54

I'm pretty sure there is a connection with thi very issue.
