### ISSUE TITLE
Lazy loading slides

### ISSUE THREAD

**Issue by pcmill** [webslides/WebSlides#8]
When I tried out the "Landing" [demo](https://webslides.tv/demos/landings) it needed a while to load the whole presentation. It seems the many images and maye other assets on the slides could be lazy loaded to speed up the application.

**Comment by jlantunez** [comment]
We are working on it. Thanks, Pieter :)

**Comment by Belelros** [comment]
@pcmill we've discussed this a bit and I wanted to get your opinion too. I don't see how lazyloading helps to speed up the application since stuff will be loading anyway. JavaScript should be quick to arrive and once it executes it will make the things work, although images and stuff might not be there yet, it won't matter.

How would it benefit from lazyloading then?

The way I see lazyloading benefits a page so DOM is ready early and then additional content starts loading in parallel so the text and styles are already there. However, in this case, you need all the things there in order to actually do the presentation. You don't want to start sliding and stuff still be coming in, right?

Please let me know if there's anything I've missed here.

**Comment by Belelros** [comment]
Closing this although up to be reopened if we get valid usecases.

**Comment by esitesnet** [comment]
I had a use case where I had some 50 slides, all with heavy images in background and foreground along with some iframes hosted on in a website. The total size of all images was around 39 Mb, so i needed some form of lazy load.

I made a small plugin to lazy load the images using [[be]lazy.js (http://dinbror.dk/blazy/)](http://dinbror.dk/blazy/)

```
<script type="text/javascript" src="js/blazy.js"></script>
<script type="text/javascript">
// Start Blazy before Webslides
window.bLazy = new Blazy({ loadInvisible: false  });
// Plugin will be constructed at this time and it will receive the webslides instance.
class bLazyPlugin {
	constructor(wsInstance) {
		wsInstance.el.addEventListener('ws:slide-change', bLazyPlugin.onSectionEnabled_);
	}

	// The lazy loading parts of the next slide will be loaded
	static onSectionEnabled_(event) {
		// Get all the DOM elements with class b-lazy in the next slide
		var slidedom = document.querySelectorAll("#section-" + (event.detail.currentSlide + 1) + " .b-lazy"); 
		// Force Blazy to load all the lazy loading parts of next slide
		bLazy.load( slidedom, true);
	}
}

// Adding the plugin to WebSlides
WebSlides.registerPlugin('bLazy', bLazyPlugin);

// Starting WebSlides
window.ws = new WebSlides();
</script>

```
Hope this helps someone.
