### ISSUE TITLE
Bower package

### ISSUE THREAD

**Issue by kevincizik** [webslides/WebSlides#83]
Would it be possible, please, to register this repo to bower?
Thanks

**Comment by Belelros** [comment]
Hi @kevincizik, thanks for reaching out. Unfortunately Bower is no longer in development so we won't be adding the repo to it. Since we have WebSlides published on [NPM](https://www.npmjs.com/package/webslides) you can install WebSlides with bower by using `bower install WebSlides/webslides`.

Best wishes!
